version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependency"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependency"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/*"
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      openshift:
        patterns:
          - "github.com/openshift/*"
          - "github.com/openshift-online/*"
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependency"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
